name: Commit Message Check

on:
  push:
    branches:
      - '*'

jobs:
  check_commit_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message format
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        if [[ ! "$COMMIT_MESSAGE" =~ ^\[$BRANCH_NAME\] ]]; then
          echo "Error: Commit message must be in the format: [$BRANCH_NAME] message"
          exit 1
        fi
